# Generated by Django 5.0 on 2024-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
