# Generated by Django 5.0 on 2024-02-29 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
