# Generated by Django 5.0 on 2024-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Heading',
            field=models.CharField(max_length=100),
        ),
    ]
